# Book settings
title:
author: Development Data Group
logo: docs/images/logo.png
only_build_toc_files: true

repository:
  url: https://github.com/worldbank/GEEST
  branch: main

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar: true
  extra_navbar: ""
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://worldbank.github.io/GEEST
  extra_footer: |
    <div>
     Country borders or names do not necessarily reflect the World Bank Group’s official position. All maps are for illustrative purposes and do not imply the expression of any opinion on the part of the World Bank, concerning the legal status of any country or territory or concerning the delimitation of frontiers or boundaries
    </div>
        <b>All content (unless otherwise specified) is subject to the <a href="https://opensource.org/license/mit/">MIT License.</a></b>
    </div>
  favicon: docs/images/favicon.ico
#######################################################################################
# Execution settings
execute:
  execute_notebooks: "off"

#######################################################################################
# Sphinx settings
sphinx:
  config:
    html_show_copyright: false
    html_last_updated_fmt: "%b %d, %Y"
